# Copyright 2020, akashche at redhat.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: Visual Studio 2013

clone_folder: c:\projects\jdk8u-win-ci

build: off

install:
  - cd "c:/projects"
  - git clone --depth=1 https://github.com/ojdkbuild/tools_cygwin_jdk11.git cygwin
  - git clone --depth=1 https://github.com/ojdkbuild/tools_bootjdk7.git bootjdk7
  - git clone --depth=1 https://github.com/ojdkbuild/tools_bootjdk7_32.git bootjdk7_32
  - git clone --depth=1 https://github.com/ojdkbuild/tools_toolchain_msvcr100.git msvcr100
  - git clone --depth=1 --branch VER-2-8-1 https://git.savannah.gnu.org/git/freetype/freetype2.git freetype2
  - set PATH=c:/projects/cygwin/bin;%PATH%
  - curl -LO https://builds.shipilev.net/workspaces/jdk8u-jdk8u-dev.tar.xz
  - bash -c "tar xJf jdk8u-jdk8u-dev.tar.xz"
  - cd jdk8u-jdk8u-dev
  - hg pull
  - hg up
  - bash -c "./common/bin/hgforest.sh pull"
  - bash -c "./common/bin/hgforest.sh up"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/corba"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/hotspot"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/jaxp"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/jaxws"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/jdk"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/langtools"
  - hg id
  - cd "c:/projects/jdk8u-jdk8u-dev/nashorn"

build_script:
  - cd "c:/projects/jdk8u-jdk8u-dev"
  - bash configure
        --with-debug-level=fastdebug
        --with-target-bits=32
        --with-toolchain-version=2010
        --with-msvcr-dll=c:/projects/msvcr100/i586/msvcr100.dll
        --with-boot-jdk=c:/projects/bootjdk7_32
        --with-freetype-src=c:/projects/freetype2
  - bash -c "make images"
  - build\windows-x86-normal-server-fastdebug\images\j2sdk-image\bin\java.exe -version
  - rd /s /q build
  - bash configure
        --with-debug-level=fastdebug
        --with-target-bits=64
        --with-toolchain-version=2010
        --with-msvcr-dll=c:/projects/msvcr100/amd64/msvcr100.dll
        --with-boot-jdk=c:/projects/bootjdk7
        --with-freetype-src=c:/projects/freetype2
  - bash -c "make images"
  - build\windows-x86_64-normal-server-fastdebug\images\j2sdk-image\bin\java.exe -version

